### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by divyansha** [DingKe/nn_playground#5]
I'm getting ValueError: None values not supported when using this QuasiRNN implementation with Keras 2.0.5

The following is my code:
`
def qrnn_model(nb_classes=13):
    model = Sequential()
    model.add(QRNN(128, window_size=3, dropout=0.2, batch_input_shape=(166, 200, 4)))
    model.add(Dense(nb_classes, activation='softmax'))
    return model

def train(X_train,X_test,  y_train, y_test, model, model_name, **kwargs):
    with tf.device('/gpu:1'):
        model.compile(loss='categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])
        X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2]))
        print("Type of input", type(X_train))
        print("These many NaNs", np.count_nonzero(pd.isnull(X_train)))
        model.fit(X_train, y_train, batch_size=166,validation_split=0.125, epochs=100,verbose=1)
        model.save("divyansh_%s.h5" % model_name)
        score = model.evaluate(X_test, y_test, verbose=0)
        print('Test score:', score[0])
        print('Test accuracy:', score[1])

f = np.load('all_data_just_a_new.npz')
X_train, X_test, y_train, y_test = f['arr_0'], f['arr_1'], f['arr_2'], f['arr_3'],
model = qrnn_model()
train(X_train,X_test,  y_train, y_test, model, 'qrnn_model')
`

**Comment by nigeljyng** [comment]
hey @divyansha, did you figure out how to make it work? I'm getting the same error.

```python
>>> model.predict(x[:5])  # this one works
array([[ 0.48886532],
       [ 0.5698421 ]], dtype=float32)

>>> model.fit(x[:2], y[:2])   # this one doesn't
ValueError: None values not supported.
```

I'm using Keras (2.0.8) with tensorflow (1.3.0) as the backend.
