### ISSUE TITLE
states_value parameter is missing from QRNN

### ISSUE THREAD

**Issue by lminer** [DingKe/nn_playground#9]
On line 124 of qrnn.py, did you mean to have it read:
```
def reset_states(self, states_value=None):
```
Otherwise `states_value` will never exist.

**Comment by lminer** [comment]
Also.
Line 204: Should this be an elif?
Line 266: ouput should be output
line 311: Should be activity_regularizer

**Comment by DingKe** [comment]
Fixed. Many thanks for pointing out.
